#!/bin/bash

set -e

THIS_DIRECTORY="$(dirname $(readlink -f $0))"
LOLLIPOP_TARGET_DIRECTORY=${CARGO_TARGET_DIR:-${THIS_DIRECTORY}/target}

cargo build --profile incremental --manifest-path="${THIS_DIRECTORY}/tools/lollipop/Cargo.toml"
# cargo sets LD_LIBRARY_PATH which we don't want, so let's call the binary directly
"${LOLLIPOP_TARGET_DIRECTORY}/incremental/lollipop" "$@"
